# Generated by Django 4.2.8 on 2023-12-09 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Home", "0001_initial"),
        ("Coordinator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job_Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="Pending", max_length=20)),
                ("apply_date", models.DateTimeField(auto_now_add=True)),
                (
                    "job_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Coordinator.job",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.student"
                    ),
                ),
            ],
        ),
    ]
