# Generated by Django 4.2.8 on 2023-12-09 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("res", models.FileField(upload_to="res/")),
                ("topic", models.CharField(max_length=30)),
                (
                    "department_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Admin.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CompanyName", models.CharField(max_length=30)),
                ("post", models.CharField(max_length=30)),
                ("no_of_vacancy", models.IntegerField()),
                ("cgpa", models.FloatField()),
                ("back_logs", models.IntegerField()),
                ("last_date", models.DateField()),
                ("package", models.FloatField()),
                ("bond", models.IntegerField()),
                (
                    "department_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Admin.department",
                    ),
                ),
            ],
        ),
    ]
